// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        hn: string;
        "hn-comment": string;
        "hn-comment-count": string;
        "hn-post": string;
        "hn-post-back": string;
        "hn-post-comments-link": string;
        "hn-post-list": string;
        "hn-post-title": string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
