// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        comments: string
        hn: string
        post: string
        title: string
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss

export = StyleCssModule
