#!/bin/zsh
docker ps -q --filter ancestor="taybart.com" | xargs -r docker stop
docker rm -v $(docker ps -a -q -f status=exited)
docker load --input taybart.com
docker run -d --restart unless-stopped -p 8080:8080 taybart.com
