// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        active: string;
        "darkmode-toggle": string;
        header: string;
        "header-left": string;
        "header-right": string;
        "nav-link": string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
