// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        active: string
        header: string
        left: string
        'nav-link': string
        right: string
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss

export = StyleCssModule
