// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        back: string
        by: string
        comment: string
        'comment-bottom': string
        comments: string
        count: string
        post: string
        title: string
        'title-link': string
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss

export = StyleCssModule
